
default: &default
  adapter: postgresql
  encoding: unicode
  host: ec2-54-163-228-0.compute-1.amazonaws.com
  username: pgplguxdorwwsu
  database: d1lpi6jekglu35

development:
    adapter: sqlite3
    pool: 5
    timeout: 5000
    database: db/development.sqlite3


test:
  <<: *default


production:
  <<: *default


#
#default: &default
#  adapter: postgresql
#  encoding: unicode
#  host: ec2-54-163-228-0.compute-1.amazonaws.com
#  username: brennan.bata
#  database: d1lpi6jekglu35
#
#development:
#  <<: *default
#
#
#test:
#  <<: *default
#  database: db/test.sqlite3
#
#production:
#  <<: *default